export const FETCH_SOURCE_REQUEST = "FETCH_SOURCE_REQUEST";
export const FETCH_SOURCE_SUCCESS = "FETCH_SOURCE_SUCCESS";
export const FETCH_SOURCE_FAILURE = "FETCH_SOURCE_FAILURE";

export const FETCH_FILTERED_DATA_REQUEST = "FETCH_FILTERED_DATA_REQUEST";
export const FETCH_FILTERED_DATA_SUCCESS = "FETCH_FILTERED_DATA_SUCCESS";
export const FETCH_FILTERED_DATA_FAILURE = "FETCH_FILTERED_DATA_FAILURE";

export const FILTERBYSEARCH = "FILTERBYSEARCH"


// export const BOOKMARK