export const FETCH_SOURCE_REQUEST = "FETCH_SOURCE_REQUEST";
export const FETCH_SOURCE_SUCCESS = "FETCH_SOURCE_SUCCESS";
export const FETCH_SOURCE_FAILURE = "FETCH_SOURCE_FAILURE";

export const FETCH_FILTERED_DATA_REQUEST = "FETCH_FILTERED_DATA_REQUEST";
export const FETCH_FILTERED_DATA_SUCCESS = "FETCH_FILTERED_DATA_SUCCESS";
export const FETCH_FILTERED_DATA_FAILURE = "FETCH_FILTERED_DATA_FAILURE";

export const FILTERBYSEARCH = "FILTERBYSEARCH"

export const FILTERBYLANGUAGEREQUEST = "FILTERBYLANGUAGEREQUEST"
export const FILTERBYLANGUAGESUCCESS = "FILTERBYLANGUAGESUCCESS"
export const FILTERBYLANGUAGEFAILURE = "FILTERBYLANGUAGEFAILURE"

export const POSTSTORY = "POSTSTORY"
export const POSTSTORYSUCCESS = "POSTSTORYSUCCESS"
export const POSTSTORYFAILURE = "POSTSTORYFAILURE"

export const BOOKMARK_REQUEST = "BOOKMARK_REQUEST"
export const BOOKMARK_SUCCESS = "BOOKMARK_SUCCESS"
export const BOOKMARK_FAILURE = "BOOKMARK_FAILURE"

export const GET_BOOKMARK_REQUEST = "GET_BOOKMARK_REQUEST"
export const GET_BOOKMARK_SUCCESS = "GET_BOOKMARK_SUCCESS"
export const GET_BOOKMARK_FAILURE = "GET_BOOKMARK_FAILURE"